---
title: "Untitled"
author: "Scott Bek"
date: '2021 3 11 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages

library(dplyr)
library(lubridate)
library(skimr)
library(tidyverse)
library(rstanarm)
library(xtable)
library(readxl)
library(broom.mixed)
library(gtsummary)
library(gt)
library(ggdist)

```

```{r data_cleaning}
# Covid-19 data is collected from 2020/01/15 to 2021/01/14. There is one dataset
# about confirmed cases and one dataset about death cases. It might be a good
# idea to first join these two datasets together by cities. Also, I decided to create a new column called death_rate that divides total death cases by total confirmed cases.

covid_confirmed <- read_csv("final-project/data/covid19/City_Confirmed_20200115_20210114.csv",
                            col_types = 
                              cols(
                                .default = col_double(),
                                City_CH = col_character(),
                                City_EN = col_character(),
                                Prov_CH = col_character(),
                                Prov_EN = col_character()
                              ))

covid_death <- read_csv("final-project/data/covid19/City_Death_20200115_20210114.csv",
                        col_types = 
                          cols(
                            .default = col_double(),
                            City_CH = col_character(),
                            City_EN = col_character(),
                            Prov_CH = col_character(),
                            Prov_EN = col_character()
                          ))

covid <- covid_confirmed %>% 
  left_join(., covid_death, by = c("City_EN", "Prov_EN")) %>% 
  mutate(death_rate = T_D_210114 / T_C_210114)
  

# The air quality data consists for datasets for each of the 6 major pollutants:
# CO, NO2, O3, PM10, PM2.5, and SO2. The collection period is from 2020/01/01 to
# 2020/12/21. Using rowwise and c_across, I decided to calculate the average
# measure of each of the pollutants.

# CO2

co_june_to_oct <- read_csv("final-project/data/air_quality/CO.csv",
                           col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))

co_jan_to_may <- read_csv("final-project/data/air_quality/CO_20200101-20200531.csv",
                          col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))

co <- co_jan_to_may %>% 
  left_join(., co_june_to_oct, by = c("City_EN", "Prov_EN"))

co <- co %>% 
  select(City_EN, Prov_EN, starts_with("CO_Mean")) %>% 
  rowwise() %>% 
  mutate(avg_co = mean(c_across(CO_Mean_0101:CO_Mean_1221))) %>% 
  select(City_EN, Prov_EN, avg_co)

# NO2

no2_june_to_oct <- read_csv("final-project/data/air_quality/NO2.csv",
                            col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))

no2_jan_to_may <- read_csv("final-project/data/air_quality/NO2_20200101-20200531.csv",
                           col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))

no2 <- no2_jan_to_may %>% 
  left_join(., no2_june_to_oct, by = c("City_EN", "Prov_EN"))

no2 <- no2 %>% 
  select(City_EN, Prov_EN, starts_with("NO2_Mean")) %>% 
  rowwise() %>% 
  mutate(avg_no2 = mean(c_across(NO2_Mean_0101:NO2_Mean_1221))) %>% 
  select(City_EN, Prov_EN, avg_no2)

# O3

o3_june_to_oct <- read_csv("final-project/data/air_quality/O3.csv",
                           col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))

o3_jan_to_may <- read_csv("final-project/data/air_quality/O3_20200101-20200531.csv",
                          col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))

o3 <- o3_jan_to_may %>% 
  left_join(., o3_june_to_oct, by = c("City_EN", "Prov_EN"))

o3 <- o3 %>% 
  select(City_EN, Prov_EN, starts_with("O3_Mean")) %>% 
  rowwise() %>% 
  mutate(avg_o3 = mean(c_across(O3_Mean_0101:O3_Mean_1221))) %>% 
  select(City_EN, Prov_EN, avg_o3)

# PM10

pm10_june_to_oct <- read_csv("final-project/data/air_quality/PM10.csv",
                             col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))
pm10_jan_to_may <- read_csv("final-project/data/air_quality/PM10_20200101-20200531.csv",
                            col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))

pm10 <- pm10_jan_to_may %>% 
  left_join(., pm10_june_to_oct, by = c("City_EN", "Prov_EN"))

pm10 <- pm10 %>% 
  select(City_EN, Prov_EN, starts_with("PM10_Mean")) %>% 
  rowwise() %>% 
  mutate(avg_pm10 = mean(c_across(PM10_Mean_0101:PM10_Mean_1221))) %>% 
  select(City_EN, Prov_EN, avg_pm10)

# PM2.5

pm2.5_june_to_oct <- read_csv("final-project/data/air_quality/PM2.5.csv",
                              col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))

pm2.5_jan_to_may <- read_csv("final-project/data/air_quality/PM2.5_20200101-20200531.csv",
                             col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))

pm2.5 <- pm2.5_jan_to_may %>% 
  left_join(., pm2.5_june_to_oct, by = c("City_EN", "Prov_EN"))

pm2.5 <- pm2.5 %>% 
  select(City_EN, Prov_EN, starts_with("PM2.5_Mean")) %>% 
  rowwise() %>% 
  mutate(avg_pm2.5 = mean(c_across(PM2.5_Mean_0101:PM2.5_Mean_1221))) %>% 
  select(City_EN, Prov_EN, avg_pm2.5)

# SO2

so2_june_to_oct <- read_csv("final-project/data/air_quality/SO2.csv",
                            col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))

so2_jan_to_may <- read_csv("final-project/data/air_quality/SO2_20200101-20200531.csv",
                           col_types =
                             cols(
                               .default = col_double(),
                               City_CH = col_character(),
                               City_EN = col_character(),
                               Prov_CH = col_character(),
                               Prov_EN = col_character()
                             ))

so2 <- so2_jan_to_may %>% 
  left_join(., so2_june_to_oct, by = c("City_EN", "Prov_EN"))

so2 <- so2 %>% 
  select(City_EN, Prov_EN, starts_with("SO2_Mean")) %>% 
  rowwise() %>% 
  mutate(avg_so2 = mean(c_across(SO2_Mean_0101:SO2_Mean_1221))) %>% 
  select(City_EN, Prov_EN, avg_so2)

# Now that I have cleaned the datasets on both COVID-19 and air quality, I
# decided to combine all of them into a single covid_aq tibble, and save it into
# a new csv file. This way, I can simply call on this new csv file whenever I
# want to perform visualization and/or data analysis.

covid_aq <- covid %>% 
  left_join(., co, by = c("City_EN", "Prov_EN")) %>%
  left_join(., no2, by = c("City_EN", "Prov_EN")) %>% 
  left_join(., o3, by = c("City_EN", "Prov_EN")) %>% 
  left_join(., pm10, by = c("City_EN", "Prov_EN")) %>% 
  left_join(., pm2.5, by = c("City_EN", "Prov_EN")) %>% 
  left_join(., so2, by = c("City_EN", "Prov_EN")) %>% 
  select(City_EN, Prov_EN, death_rate, T_C_210114, T_D_210114, avg_co, avg_no2,
         avg_o3, avg_pm10, avg_pm2.5, avg_so2)

# Adding population data. Looking at the index, A101004_10 is a column for total
# population in 2010 and Shape_Area is a column for total area of city in GIS.
# Let's rename these two columns to something meaningful.

pop <- read_xlsx("final-project/data/population/City0010.xlsx") %>% 
  rename(total_pop = A101004_10,
         total_area = Shape_Area)

# Now let's merge the population data with covid_aq using left_join. Also, we
# want to select columns that are necessary.

covid_aq <- covid_aq %>% 
  left_join(., pop, by = c("City_EN", "Prov_EN")) %>% 
  select(City_EN, Prov_EN, death_rate, T_C_210114, T_D_210114, avg_co, avg_no2,
         avg_o3, avg_pm10, avg_pm2.5, avg_so2, total_pop, total_area)

# Now that I have a tibble called covid_aq that contains all of the columns of
# interest, let's save it into a new csv file! Notice that I'm commenting out
# the write_csv since I don't want to overwrite it everytime I run this code
# chunk.

## write_csv(covid_aq, "final-project/clean/covid_aq.csv")

```

```{r covid_death_plot}
# COVID-19 death rate plot (city-level)

# Here, I want to make a bar graph that shows which of the cities in China have
# high COVID-19 death rates. By filling with total cases at the end of the
# collection period, I try to show that cities with many total cnfirmed cases
# don't necessarily have high death rates.

covid_aq %>% 
  arrange(desc(death_rate)) %>% 
  filter(death_rate > 0.07) %>% 
  ggplot(aes(x = City_EN,
             y = death_rate,
             fill = T_C_210114)) +
  geom_col() +
  coord_flip() +
  labs(title = "Top 10 Chinese Cities with Highest COVID-19 Death Rate",
       subtitle = "Having many total cases doesn't necessarily mean having high death rates!",
       x = "Cities",
       y = "Death Rates",
       fill = "Total Cases",
       caption = "Source: Harvard Dataverse") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_classic()

# COVID-19 death rate plot (province-level)

# I do the same, but this time with provinces instead of cities. It might be
# more intuitive if I could show this using the map of China, but for now let's
# settle on the bar plots.

covid_aq %>% 
  arrange(desc(death_rate)) %>% 
  filter(death_rate > 0.07) %>% 
  ggplot(aes(x = Prov_EN,
             y = death_rate,
             fill = T_C_210114)) +
  geom_col() +
  coord_flip() +
  labs(title = "Top 10 Chinese Provinces with Highest COVID-19 Death Rate",
       subtitle = "Having many total cases doesn't necessarily mean having high death rate!",
       x = "Provinces",
       y = "Death Rates",
       fill = "Total Cases",
       caption = "Source: Harvard Dataverse") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_classic()

```

```{r covid_aq_scatter_plot}
# For the following scatter plots, the goal is to show whether the correlation
# between COVID death rate and each of the pollutants is weak or strong. Since
# we will use the same format for all pollutants (changing the variables using
# if, else), we only need to make one plot with appropriate aesthetics.

# Scatter plot (Covid death rate vs CO)

covid_aq %>% 
  filter(death_rate != 0) %>% 
  ggplot(aes(x = avg_co,
             y = death_rate)) +
  geom_point(na.rm = TRUE) +
  geom_smooth(method = "lm",
              formula = y ~ x,
              na.rm = TRUE) +
  labs(title = "Correlation between COVID-19 death rate and CO",
       subtitle = "Seems like there is a weak correlation between the two",
       x = "Average CO",
       y = "Death Rates",
       caption = "Source: Harvard Dataverse") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_bw()

# Scatter plot (Covid death rate vs NO2)

covid_aq %>% 
  filter(death_rate != 0) %>% 
  ggplot(aes(x = avg_no2,
             y = death_rate)) +
  geom_point(na.rm = TRUE) +
  geom_smooth(method = "lm",
              formula = y ~ x,
              na.rm = TRUE)

# Scatter plot (Covid death rate vs O3)

covid_aq %>% 
  filter(death_rate != 0) %>% 
  ggplot(aes(x = avg_o3,
             y = death_rate)) +
  geom_point(na.rm = TRUE) +
  geom_smooth(method = "lm",
              formula = y ~ x,
              na.rm = TRUE)

# Scatter plot (Covid death rate vs PM10)

covid_aq %>% 
  filter(death_rate != 0) %>% 
  ggplot(aes(x = avg_pm10,
             y = death_rate)) +
  geom_point(na.rm = TRUE) +
  geom_smooth(method = "lm",
              formula = y ~ x,
              na.rm = TRUE)

# Scatter plot (Covid death rate vs PM2.5)

covid_aq %>% 
  filter(death_rate != 0) %>% 
  ggplot(aes(x = avg_pm2.5,
             y = death_rate)) +
  geom_point(na.rm = TRUE) +
  geom_smooth(method = "lm",
              formula = y ~ x,
              na.rm = TRUE)

# Scatter plot (Covid death rate vs SO2)

covid_aq %>% 
  filter(death_rate != 0) %>% 
  ggplot(aes(x = avg_so2,
             y = death_rate)) +
  geom_point(na.rm = TRUE) +
  geom_smooth(method = "lm",
              formula = y ~ x,
              na.rm = TRUE)

```


```{r regression_1}
# For the fitted model, I decided to remove all rows with death rate = 0, since
# I wanted to focus on cities with at least one death case. 

covid_aq_no_zero <- covid_aq %>% 
  filter(death_rate != 0)

# Since the plot above showed strong correlation only between death rate and
# SO2, let's regress death_rate on avg_so2. Also, let's control for population
# and area since intuitively they are related to the death rate.

fit_1 <- stan_glm(data = covid_aq_no_zero,
         formula = death_rate ~ avg_so2 + total_pop + total_area, 
         seed = 13,
         refresh = 0)

table_1 <- tbl_regression(fit_1, 
               intercept = TRUE, 
               estimate_fun = function(x) style_sigfig(x, digits = 10)) %>%
  
  # Since the coefficients are relatively small, let's use digits = 10.
  
  as_gt() %>% 
  cols_label(estimate = md("**Parameter**")) %>%
  tab_header(title = md("**COVID-19 Death Rate**"),
             subtitle = "How SO2, Population, and Land Area Predict COVID-19 Death Rates") %>% 
  
  # We always want our tables or plots to stand alone. Therefore, adding
  # descriptive titles is always a good idea!
  
  tab_source_note(md("Source: Harvard Dataverse"))

# Let's comment out gtsave so that we don't accidently overwrite it.

## gtsave(table_1, filename = "final-project/www/table_1.png")

# Although saving fit_1 using saveRDS and using it to produce table_1 inside
# app.R would be more preferred, doing so led to a deployment error.

```

```{r regression_2}
newobs <- tibble(avg_so2 = c(0, 10, 20, 30, 40),
                 total_pop = 5525020,
                 total_area = 1.45)

# Here, we want our newobs to contain the average SO2 level of 5 different
# cities. Since we are mainly interested in SO2, we can plug in average values
# for city population and city size.

pe <- posterior_epred(fit_1,
                newdata = newobs) %>% 
  as_tibble() %>% 
  
  # The result we get from using posterior_epred is not a tibble. Thus,
  # converting the results into a tibble is a good idea!
  
  rename("SO2-0" = `1`,
         "SO2-10" = `2`,
         "SO2-20" = `3`,
         "SO2-30" = `4`,
         "SO2-40" = `5`) %>% 
  
  # As usual, renaming the column names into something meaningful is always a
  # good idea.
  
  pivot_longer(cols = everything(),
               names_to = "groups",
               values_to = "outcome")

  # Since we want to make five distributions separated by SO2 levels, we use
  # pivot longer to separate SO2 levels and their respective outcome values.

# Let's comment out saveRDS so that we don't accidently overwrite it.

## saveRDS(pe, file = "final-project/pe.rds")

pe %>% 
  ggplot(aes(x = outcome,
             fill = groups)) +
  geom_histogram(aes(y = after_stat(count/sum(count))),
                 alpha = 0.5,
                 bins = 100,
                 position = "identity") +
  
  # Just as a reminder, this is our usual histogram arguments. Since there are
  # some overlaps between the five distributions, we want to set alpha to some
  # value less than 1.
  
  scale_x_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = seq(-0.05, 0.2, 0.01)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  # We want both our x- and y-axis in percent format. Also, by setting accuracy
  # equal to 1, we can get rid of any decimal points.
  
  labs(title = "Posterior Distribution of the Expected Value of the COVID-19 Death Rate",
       subtitle = "Cities with SO2 level above the permissible level (20) are likely to have COVID-19 death rates \nmore than twice as high COVID-19 death rates as cities with SO2 level below the permissible level",
       x = "COVID-19 Death Rate",
       y = NULL,
       fill = "SO2 Level \n(Micrograms per Cubic Meter)",
       caption = "Source: Harvard Dataverse") +
  
  # Using \n helps us avoid the texts running over the page since \n means new
  # line.
  
  theme_bw() +
  theme(legend.position = "bottom")

```

